apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - log-output/manifests/configmap.yaml
  - log-output/manifests/deployment.yaml
  - log-output/manifests/ingress.yaml
  - log-output/manifests/persistentvolumeclaim.yaml
  - log-output/manifests/service.yaml
  - ping-pong/manifests/deployment.yaml
  - ping-pong/manifests/service.yaml
  - ping-pong/manifests/statefulset.yaml
