apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-app
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-app
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app
          image: REGISTRY/TODO_APP_IMAGE
          volumeMounts:
            - name: todo-app
              mountPath: /usr/src/app/public/images
          resources:
            limits:
              cpu: '200m'
              memory: '40Mi'
