apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-output-volume
          emptyDir: {}
        - name: shared
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: hash-generator
          image: vesajo/hash-generator@sha256:a7a13955b47b9ce145fa1511e7fde1e771505c49b52e18e4dc4cc48b425b8322
          volumeMounts:
            - name: log-output-volume
              mountPath: /usr/src/app/files
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
        - name: hash-outputter
          image: vesajo/hash-outputter@sha256:6d2b759604c053b41589117b47deaf53b162d1bfe4926bf5d72886dca6a78c8a
          volumeMounts:
            - name: log-output-volume
              mountPath: /usr/src/app/files
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
