apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-claim
spec:
  storageClassName: log-output-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
