apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: ping-pong
          image: vesajo/ping-pong@sha256:1490c241ef027222aeb006a4fcde93e5e69806842fb376b1259bd32a32510218
          volumeMounts:
            - name: shared
              mountPath: /usr/src/app/shared
