apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0/oMhyZ2RP+ayBxsfJYmImvP/DGNscEgz4HALg==,iv:LfEpkvLu+Drp8ETiLhK1inq7E6ejaEUTBPcBLfmfXgo=,tag:ebs0ASiyBXgk2XKOen6njQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvK25TUHlZTE5zN2ZuVng5
            UUorV2dYWm9icHdDUFE1U3VlRGp6dEt3R0hjCmVFcHJES25ZMU1YRllMQjNVeE9w
            enh2V1pna2ZuRnhnL3l3YUErRHR5cW8KLS0tIFJKQkdLZWxoUm9hamNXdDFCT29a
            NDhyMW9CLzZlZ3J6SmJSZ3RScmhYcUUKTBHHUwUcufdWSLrNZP/1/OiqaMSW5LQD
            LKCvJWaQ+kHuaqCnae/XYA6nAHChfC1tWd21vaeHW8lfoH2UuWZ6Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T15:23:30Z"
    mac: ENC[AES256_GCM,data:EWSaTTUaf9+Lbt2W5FhOPmmdaWIw1zuN7CpAykAhcYKfL07DuJS0QyI5BM5HCVfo7zYeJc0uO4Y5tToJ3/Nq7KZs76nB0AFnFlRvZ4Myn0yzR70g8YZk5dJtwYK/2jXPEojYN4gabTyg8xe/+cv7wSXkAn52i/r3KA7d0bew8TI=,iv:a4PsoLyk1cFHCuukZwhStJ+WRZ/OI1JfDPGS3h2kt88=,tag:vICp2jUv3rgacRoTL3gzuw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.3
