apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/ingress.yaml
  - todo-app/manifests/persistentvolumeclaim.yaml
  - todo-app/manifests/service.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - todo-backend/manifests/statefulset.yaml
  - todo-backend/manifests/hourly-todo-cronjob.yaml
images:
  - name: REGISTRY/TODO_APP_IMAGE
    newName: vesajo/todo-app@sha256:f89e2f5d27b08212de0e20a20fa705cf2515ba3035b0acb3ac003f95334c9ade
  - name: REGISTRY/TODO_BACKEND_IMAGE
    newName: vesajo/todo-backend@sha256:d3d192c5ccfb1685fbe6f023cb0ace64bb6cf781eb2b473274e89c85f65eff09
