apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/ingress.yaml
  - todo-app/manifests/persistentvolumeclaim.yaml
  - todo-app/manifests/service.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - todo-backend/manifests/statefulset.yaml
  - todo-backend/manifests/cronjob.yaml
