apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: vesajo/ping-pong@sha256:b68ca8cf39635d118bc0ad2b4bd8393549916dd92cc2a0eb8d4a3f6062f97b01
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /pingpong/healthz
              port: 3001
          env:
            - name: PGHOST
              value: postgres-svc
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              cpu: '250m'
              memory: '100Mi'
            requests:
              cpu: '50m'
              memory: '30Mi'
