apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: todo-app
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:MPqxx1A+v7Rmke+rxeiNkyZOcQu5WT3OurupjQ==,iv:kaojZYFDbxMgNYjtA+y0KtamUromML1UaUOKo7uKeNg=,tag:HQkilvXlov3pv5v9DMLTHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQlR4ZWVOWDlxMExzbkZl
            SVVYL0docHpJTE1LNnkrVlF6OFJuNjk4SkJFClRZWGhCcnBMamhjcEs0bG1UUnRL
            YXdaQjRiMjM5Uy9EKzNqL2tKZk5IeDQKLS0tIGcvRmdNNzYrdVNkMnNEYnM5cEZI
            TVUwYzhyNWRIdlV3M1Y4UDlNSng4aFEKLGuo2CpRoKfKP45WCoXYXf0XXc8zuPD1
            PkXSO/O62sXhs88DuGI5AlQkPeuF04ZkUqEyhlx2kgFc4Hxe5sWHXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-25T14:16:28Z"
    mac: ENC[AES256_GCM,data:hKccdq2aD0COOV+6May0FvyDTIzIbNePJcOt3xzpAn5lHJQLf67exlWQuCvjSvtPJFmwIdqBC0nLuVmW0aUiTzrBLT4ptDmyd2seqSmMUmh6kFlvWWy+acy+D99bZS4IA3u9kHmCbCfhHamBhn8GdoFpC9ygZVgjlKKs0/gt+VY=,iv:pSosnIApJge0UovweVuxMjlFZzDeNfQu8XdWrBv1Lb4=,tag:ddNyHVnsEgGsvM1AeWhJsw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.3
