apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-app
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: REGISTRY/TODO_BACKEND_IMAGE
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /todos/healthz
              port: 3002
          env:
            - name: PGHOST
              value: postgres-svc
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              cpu: '250m'
              memory: '100Mi'
            requests:
              cpu: '100m'
              memory: '40Mi'
